import './globals.css';

import Navbar from './components/Navbar/index';
import Footer from './components/Footer/Footer';
import { EdgeStoreProvider } from '../lib/edgestore';
import Script from 'next/script';
import Providers from './components/Providers';
export const metadata = {
  title: 'apniVidya',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <html lang="en" suppressHydrationWarning>
        <head />
        
        <body className={`bg-white dark:bg-black flex flex-col `} >
        <Providers>
          <EdgeStoreProvider>
          <div>
              <Navbar />
              
        {children}
        </div>
       <div></div>
        <Footer />
         
          </EdgeStoreProvider>
      
          </Providers>
      </body>
    </html>
    <Script src="https://checkout.razorpay.com/v1/checkout.js"
    />
    </>
  )
}
