import './globals.css';
import ThemeProvider from './components/Providers/ThemeContext';
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/Footer';
import { EdgeStoreProvider } from '../lib/edgestore';
export const metadata = {
  title: 'eLearning',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
        <head />
        <body className={`flex flex-col items-center justify-center  `} >
          <EdgeStoreProvider>
          <ThemeProvider
          >
              <Navbar />
        {children}
       
        <Footer />
          </ThemeProvider>
          </EdgeStoreProvider>
      
      
      </body>
    </html>
  )
}
